### ISSUE TITLE
aws_iam_service_linked_role.es doesn't work more than once

### ISSUE THREAD

**Issue by atrull** [terraform-community-modules/tf_aws_elasticsearch#23]
I've already got the linked role done, and furthermore... I want to use this module twice. Can we make this module 'understand' that the linked role has already been done ?

Error: Error applying plan:

2 error(s) occurred:

* aws_iam_service_linked_role.es: 1 error(s) occurred:

* aws_iam_service_linked_role.es: Error creating service-linked role with name es.amazonaws.com: InvalidInput: Custom suffix is not allowed for es.amazonaws.com
	status code: 400, request id: 0f81683e-4024-11e9-a6db-c562a0c3ba05
* module.es2.aws_iam_service_linked_role.es: 1 error(s) occurred:

* aws_iam_service_linked_role.es: Error creating service-linked role with name es.amazonaws.com: InvalidInput: Service role name AWSServiceRoleForAmazonElasticsearchService has been taken in this account, please try a different suffix.
	status code: 400, request id: 0f82525c-4024-11e9-8849-4b98e6ba2d71

**Comment by antonbabenko** [comment]
Thank you for opening this issue.

I've just fixed it by allowing conditional creation of IAM service linked role in [v0.8.0](https://github.com/terraform-community-modules/tf_aws_elasticsearch/releases/v0.8.0) which has been just released.

To use it you need to specify `create_iam_service_linked_role = false` as an argument in `es2` module block.
