### ISSUE TITLE
Suppor for authentication 

### ISSUE THREAD

**Issue by hendrixroa** [terraform-community-modules/tf_aws_elasticsearch#26]
AWS has launched a new feature to authenticate with cognito, it will be supported here ?

**Comment by core-tec** [comment]
@hendrixroa Any reason you closed this issue? This feature seems to be still missing in `tf_aws_elasticsearch`.

**Comment by hendrixroa** [comment]
Yes, it is. Aws Elasticsearch support cognito.

**Comment by jamesopti** [comment]
I have the same question - How can I configure the cognito setting with this module?
