### ISSUE TITLE
Request: Terraform 0.12 support

### ISSUE THREAD

**Issue by bflugon** [terraform-community-modules/tf_aws_elasticsearch#27]
Terraform 0.12 has recently been released, which uses a different syntax for its code. Luckily terraform provides a tool for upgrading the code, so it should be easily done.

**Comment by FernandoMiguel** [comment]
+1

**Comment by antonbabenko** [comment]
[v1.0.0](https://github.com/terraform-community-modules/tf_aws_elasticsearch/releases/v1.0.0) has been released for Terraform 0.12 users.
