### ISSUE TITLE
[Feature Request] prevent destroy

### ISSUE THREAD

**Issue by worldtiki** [terraform-community-modules/tf_aws_elasticsearch#45]
Terrafom has this nice feature called prevent_destroy to reject plans which would otherwise destroy the objects associated with the resource.

This feature seems to be widely used in other projects (including other alternatives to this ES module). Would it make sense to add it in here (configurable)? I'm happy to create a pr with these changes.

https://www.terraform.io/docs/configuration/resources.html#prevent_destroy

**Comment by antonbabenko** [comment]
`prevent_destroy` as well as other `lifecycle` meta-arguments  is not possible to parametrize with variable (an error will be `Variables may not be used here.`), so it can't be part of the reusable module.
