### ISSUE TITLE
Why enable dedicated master node requires more than 10 instances?

### ISSUE THREAD

**Issue by zhaoyi0113** [terraform-community-modules/tf_aws_elasticsearch#46]
Thanks for creating this module and I'd like to know `why enable dedicated master node requires more than 10 instances?`. 

https://github.com/terraform-community-modules/tf_aws_elasticsearch/blob/6b9bcca3780996e8f0639226fdcecc953bf29860/main.tf#L45

**Comment by antonbabenko** [comment]
> Enable or disable dedicated master nodes. Dedicated master nodes increase cluster stability and are required for domains that have instance counts greater than 10. We recommend three dedicated master nodes for production domains.

From [AWS docs](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomains).

I guess this was just the best guess by the module developers, and you can provide another value of `dedicated_master_threshold` it if you want.

**Comment by zhaoyi0113** [comment]
Thanks for explaining.
