### ISSUE TITLE
Status of the Elasticseartch module

### ISSUE THREAD

**Issue by ghost** [terraform-community-modules/tf_aws_elasticsearch#56]
Hello,

We are looking for a maintained module for Elasticsearch/OpenSearch on AWS. There are not so much of them, but almost all are not updated for a long period of time

Just 7 of 19 modules were updated this year. We didn't try any of them yet, but looking at the most popular of the them, in the Issues, PR looks like there is not so much activity...

@antonbabenko

1. What is the status of this module?
2. Can it be updated, moved to the [terraform-aws-modules](/terraform-aws-modules) and added to the Terraform Registry?
3. Is there a way to participate in this process?

### [Registry - elasticsearch](https://registry.terraform.io/search/modules?q=elasticsearch)
| #  | Module                                                                                                                      | Latest update                                                                                                              |
| -- | --------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------- |
| 1  | [cloudposse/elasticsearch](https://registry.terraform.io/modules/cloudposse/elasticsearch/aws/latest)                       | Published February 15, 2022 by [cloudposse](https://registry.terraform.io/namespaces/cloudposse)                           |
| 2  | [lgallard/elasticsearch](https://registry.terraform.io/modules/lgallard/elasticsearch/aws/latest)                           | Published June 14, 2022 by [lgallard](https://registry.terraform.io/namespaces/lgallard)                                   |
| 3  | [egarbi/es-cluster](https://registry.terraform.io/modules/egarbi/es-cluster/aws/latest)                                     | Published December 17, 2020 by [egarbi](https://registry.terraform.io/namespaces/egarbi)                                   |
| 4  | [clouddrove/elasticsearch](https://registry.terraform.io/modules/clouddrove/elasticsearch/aws/latest)                       | Published May 18, 2022 by [clouddrove](https://registry.terraform.io/namespaces/clouddrove)                                |
| 5  | [vmfarms/elasticsearch](https://registry.terraform.io/modules/vmfarms/elasticsearch/aws/latest)                             | Published October 23, 2022 by [vmfarms](https://registry.terraform.io/namespaces/vmfarms)                                  |
| 6  | [corpit-consulting-public/es-cluster](https://registry.terraform.io/modules/corpit-consulting-public/es-cluster/aws/latest) | Published October 9, 2020 by [corpit-consulting-public](https://registry.terraform.io/namespaces/corpit-consulting-public) |
| 7  | [admintome/elk](https://registry.terraform.io/modules/admintome/elk/aws/latest)                                             | Published October 17, 2017 by [admintome](https://registry.terraform.io/namespaces/admintome)                              |
| 8  | [hendrixroa/cognito-elasticsearch](https://registry.terraform.io/modules/hendrixroa/cognito-elasticsearch/aws/latest)       | Published February 13, 2021 by [hendrixroa](https://registry.terraform.io/namespaces/hendrixroa)                           |
| 9  | [lablabs/elasticsearch](https://registry.terraform.io/modules/lablabs/elasticsearch/aws/latest)                             | Published September 14, 2021 by [lablabs](https://registry.terraform.io/namespaces/lablabs)                                |
| 10 | [Aplyca/elasticsearch](https://registry.terraform.io/modules/Aplyca/elasticsearch/aws/latest)                               | Published February 14, 2019 by [Aplyca](https://registry.terraform.io/namespaces/Aplyca)                                   |
| 11 | [viceIII/elasticsearch](https://registry.terraform.io/modules/viceIII/elasticsearch/aws/latest)                             | Published February 20, 2018 by [viceIII](https://registry.terraform.io/namespaces/viceIII)                                 |
| 12 | [dod-iac/elasticsearch-domain](https://registry.terraform.io/modules/dod-iac/elasticsearch-domain/aws/latest)               | Published July 31, 2020 by [dod-iac](https://registry.terraform.io/namespaces/dod-iac)                                     |
| 13 | [rameshcreations/es](https://registry.terraform.io/modules/rameshcreations/es/aws/latest)                                   | Published October 7, 2020 by [rameshcreations](https://registry.terraform.io/namespaces/rameshcreations)                   |
| 14 | [JamesWoolfenden/elastic](https://registry.terraform.io/modules/JamesWoolfenden/elastic/aws/latest)                         | Published September 20, 2022 by [JamesWoolfenden](https://registry.terraform.io/namespaces/JamesWoolfenden)                |
| 15 | [foss-cafe/elasticsearch](https://registry.terraform.io/modules/foss-cafe/elasticsearch/aws/latest)                         | Published December 22, 2020 by [foss-cafe](https://registry.terraform.io/namespaces/foss-cafe)                             |
| 16 | [moroleandro/es-cluster](https://registry.terraform.io/modules/moroleandro/es-cluster/aws/latest)                           | Published April 27, 2021 by [moroleandro](https://registry.terraform.io/namespaces/moroleandro)                            |
| 17 | [infrablocks/elasticsearch-domain](https://registry.terraform.io/modules/infrablocks/elasticsearch-domain/aws/latest)       | Published May 30, 2021 by [infrablocks](https://registry.terraform.io/namespaces/infrablocks)                              |
| 18 | [appzen-oss/elasticsearch](https://registry.terraform.io/modules/appzen-oss/elasticsearch/aws/latest)                       | Published January 11, 2022 by [appzen-oss](https://registry.terraform.io/namespaces/appzen-oss)                            |
| 19 | [pogosoftware/elasticsearch](https://registry.terraform.io/modules/pogosoftware/elasticsearch/aws/latest)                   | Published May 19, 2022 by [pogosoftware](https://registry.terraform.io/namespaces/pogosoftware)                            |

**Comment by antonbabenko** [comment]
This repository (as well as the GitHub organization itself) has been abandoned for several years.

I don't think we (maintainers) have immediate plans to add or adopt another Terraform AWS module unless we use it ourselves or for our assignments.

I have just looked at the existing links you provide; some look pretty good.
