### ISSUE TITLE
vpc_options is not a valid parameter

### ISSUE THREAD

**Issue by phelun** [terraform-community-modules/tf_aws_elasticsearch#6]
Probably im doing something wrong, when i setup my configuration, then run init, i get below error. 

 $ terraform init
Downloading modules...
Error getting plugins: module root: module es: vpc_options is not a valid parameter

My configo looks as below 
terraform Version : 0.10.7 

  1 provider "aws" {
  2   region = "eu-xxx"
  3   profile = "xxx"
  4 }
  5
  6 module "es" {
  7   source = "github.com/terraform-community-modules/tf_aws_elasticsearch?ref=0.0.1"
  8   domain_name = "my-elasticsearch-domain"
  9   vpc_options = {
 10     security_group_ids = ["sg-xxxxxx"]
 11     subnet_ids = ["subnet-xxxxx"]
 12   }
 13   instance_count = 1
 14   instance_type = "t2.medium.elasticsearch"
 15   dedicated_master_type = "t2.medium.elasticsearch"
 16   es_zone_awareness = false
 17   ebs_volume_size = 35
 18 }

Hopefully im doing something wrong someone else can spot out. 

Thanks in advance

**Comment by antonbabenko** [comment]
I see that you are referring to the wrong version of this module (`0.0.1` does not have `vpc_options`). You should use this one:
```
source = "github.com/terraform-community-modules/tf_aws_elasticsearch?ref=v0.1.0"
```

**Comment by sddhrthrt** [comment]
Can we please have updated README.md examples that match the versions? I'm worried to use the example from the README because the version example in it is 0.0.1. Thanks for the work, though :)
