### ISSUE TITLE
Add Support for Tags

### ISSUE THREAD

**Issue by cmorgan-qc** [terraform-community-modules/tf_aws_elasticsearch#8]
Right now, it looks like the tags are hardcoded (https://github.com/terraform-community-modules/tf_aws_elasticsearch/blob/master/main.tf#L55)

We use tagging for cost reporting, so we need to be able to add our own tags to the ES resource. I'm happy to send a PR (I'll need to run it through my company's process first) to add this support if you let me know the preferred workflow.

**Comment by antonbabenko** [comment]
Tagging has been added in [v0.2.0](https://github.com/terraform-community-modules/tf_aws_elasticsearch/releases/tag/v0.2.0).
